name: PR Tests - Base
on:
  workflow_call:
    inputs:
      test-type:
        description: "Type of tests to run"
        required: true
        type: string

jobs:
  tests:
    strategy:
      max-parallel: 99
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.4.25"

      - name: Get uv cache dir
        id: pip-cache
        shell: bash
        run: |
          echo "dir=$(uv cache dir)" >> $GITHUB_OUTPUT

      - name: Load github cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: pr-uv-${{ runner.os }}-py${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            pr-uv-${{ runner.os }}-py${{ matrix.python-version }}

      - name: Install Just
        uses: extractions/setup-just@v2
        with:
          just-version: "1.36.0"

      - name: Run ${{ inputs.test-type }}
        run: |
          just ${{ inputs.test-type }}
